//Planting a tree Project 1

//Define class
public class Tree {
public static void main (String[]args){
//ensure there is a main method for program to execute

//printing a tree to the terminal and introducing myself
System.out.println("Hey there, my name is Michelle and I am practicing Java!");

System.out.println("Below is the tree that I've created");

    System.out.println("       *  ");
    System.out.println("      ***  ");
    System.out.println("    ****** ");
    System.out.println("  *********** ");
    System.out.println("*************** ");
   
    }
}